version: '3'

services:
  php:
    container_name: php-rdspj
    build: ./php
    volumes:
    - ../RentalDVDSystem:/var/www

  nginx:
    image: nginx
    container_name: nginx-rdspj
    ports:
    - 8080:80
    volumes:
    - ../RentalDVDSystem:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: db-host-rdspj
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rdspj_db
      MYSQL_USER: rdspj_db_user
      MYSQL_PASSWORD: rdspj_db_password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 13306:3306